---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xlppfnfn/public_html

    # Navigate to the repository directory
    - cd /home/xlppfnfn/repositories/react-solarich-ecorp

    # Update the Git repository (optional, if needed)
    - git pull

    # Install project dependencies (if needed)
    - npm install

    # Build the project (e.g., using npm run build)
    - npm run build

    # Deploy the built files to the specified path
    - /bin/cp -R build/* $DEPLOYPATH
