deployment:
  tasks:
    - export DEPLOYPATH=/home/xlppfnfn/public_html
    - git fetch --all
    - git reset --hard origin/main
    - npm install
    - npm run build
    - /bin/cp -R build/* $DEPLOYPATH
